username: "15639799734"
password: "F7ox0N"
root_username: "admin"
root_password: "jjyk@UAT123"
skill_project_name: "内部测试技能项目0724"
class_name: "测试班级0911测试线下申报"
id: "411521199605130914"
student_name: "张勇"
student_account: "15639799731"
code: "111111"
learning_course_name: "内部测试学习课程0724"
learning_course_username: "15639799733"
Course_url: "https://content-fbt-uat.class-demo.com/supply/index/course?cType=2"
